id: I388C8DDF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T00:47:49+00:00'
last_modified: '2022-06-07T18:05:18.874215+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25728
  title: ཀླུ་སྒྲུབ་དགོངས་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '6464':
      image_group_id: I1KG25730
      title: ''
      total_pages: 242
      order: 1
      base_file: 6464.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
