id: P003174
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25728
  title: ཀླུ་སྒྲུབ་དགོངས་རྒྱན།
  author: ''
  volumes:
    9dbd13f83bfe408c95c37b13361437ce:
      image_group_id: I1KG25730
      title: ''
      volume_number: 1
      total_pages: 242
      base_file: v001.txt
